# Generated by Django 4.0.4 on 2022-04-17 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DateOfBirthday',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Manager',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='DateOfCreation',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
